name: Build

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install cmake
        uses: lukka/get-cmake@v3.21.1
      
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_NON_SHARED=FALSE -DBUILD_SHARED=TRUE -DHAVE_ZLIB=FALSE -B build .
          cd build/libdwarf
          cmake --build .
      
      - name: Release file
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: 'libdwarf.so'
          file: 'build/libdwarf/libdwarf.so'
          tag-name: 'latest'
          release-name: 'Latest build'
      
      - uses: actions/upload-artifact@v2
        with:
          name: libdwarf-linux
          path: build/libdwarf/libdwarf.so

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Install cmake
        uses: lukka/get-cmake@v3.21.1
      
      - name: Build
        run: |
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_NON_SHARED=FALSE -DBUILD_SHARED=TRUE -DHAVE_ZLIB=FALSE -B build .
          cd build/libdwarf
          cmake --build .
      
      - name: Release file
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: 'libdwarf.dll'
          file: 'build/libdwarf/libdwarf.dll'
          tag-name: 'latest'
          release-name: 'Latest build'

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install cmake
        uses: lukka/get-cmake@v3.21.1
      
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_NON_SHARED=FALSE -DBUILD_SHARED=TRUE -DHAVE_ZLIB=FALSE -B build .
          cd build/libdwarf
          cmake --build .
      
      - name: Release file
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: 'libdwarf.dylib'
          file: 'build/libdwarf/libdwarf.dylib'
          tag-name: 'latest'
          release-name: 'Latest build'
    
    
